industries:
  label: depcore.portfolio::lang.industries.menu_label
  view:
    list: $/depcore/portfolio/models/industry/columns.yaml
    toolbarButtons: add|remove|create
  manage:
    form: $/depcore/portfolio/models/industry/fields.yaml
    showSearch: true
